### ISSUE TITLE
请问怎么调用我这个服务里面的方法？

### ISSUE THREAD

**Issue by xiaour** [mosongcc/eureka-nodejs-client#1]
eureka.instance('my-microservice').then(rs=>{
    //请问怎么调用我这个服务里面的方法？
})

**Comment by xiaour** [comment]
my-microservice 里面有个接口叫  /getUserInfo

**Comment by mosongcc** [comment]
eureka.instance('my-microservice').then(rs=>{
 // 这里rs只是返回的ip与port。
})

代码逻辑比较简单，是根据eureka的java服务抓包获取api接口实现的，可以看下代码。

**Comment by xiaour** [comment]
嗷，有时间可以实现一套Feign的方式，这样就全乎了
